github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/apache-tomcat","gcr.io/initializ-buildpacks/apache-tomcat"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            Tomcat 8
  id:              tomcat
  version_pattern: "8\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/tomcat-dependency:main
  with:
    uri: https://archive.apache.org/dist/tomcat/tomcat-8
- name:            Tomcat 9
  id:              tomcat
  version_pattern: "9\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/tomcat-dependency:main
  with:
    uri: https://archive.apache.org/dist/tomcat/tomcat-9
- name:            Tomcat 10
  id:              tomcat
  version_pattern: "10\\.0\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/tomcat-dependency:main
  with:
    uri: https://archive.apache.org/dist/tomcat/tomcat-10
    version_regex: "(10)\\.(0)\\.([\\d]+)"
- name:            Tomcat 10.1
  id:              tomcat
  version_pattern: "10\\.1\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/tomcat-dependency:main
  with:
    uri: https://archive.apache.org/dist/tomcat/tomcat-10
    version_regex: "(10)\\.(1)\\.([\\d]+)"
- id:   tomcat-access-logging-support
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  with:
    uri:         https://repo1.maven.org/maven2
    group_id:    org.cloudfoundry
    artifact_id: tomcat-access-logging-support
    version_regex: "^[\\d]+\\.[\\d]+\\.[\\d]+\\.RELEASE$"
    source_classifier: sources
- id:   tomcat-lifecycle-support
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  with:
    uri:         https://repo1.maven.org/maven2
    group_id:    org.cloudfoundry
    artifact_id: tomcat-lifecycle-support
    version_regex: "^[\\d]+\\.[\\d]+\\.[\\d]+\\.RELEASE$"
    source_classifier: sources
- id:   tomcat-logging-support
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  with:
    uri:         https://repo1.maven.org/maven2
    group_id:    org.cloudfoundry
    artifact_id: tomcat-logging-support
    version_regex: "^[\\d]+\\.[\\d]+\\.[\\d]+\\.RELEASE$"
    source_classifier: sources
